apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-deployment1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-cont1
          image: nginx:1.25.1
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume1
      mountPath: /usr/share/nginx/html
    volumes:
      - name: config=volime1
        configMap:
          name: configmap1
