apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment1
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: configvolume1
          mountPath: /usr/share/nginx/html/
      volumes:
      - name: configvolume1
        configMap:
          name: configmap-1

