apiVersion: v1
kind: Service
metadata:
  name: lb-service
spec:
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: LoadBalancer
